#!/bin/bash
set -euo pipefail

# =============================================================================
# OpenSharing Volumes Server — Lambda Deployment
#
# Deploys the server using CloudFormation (IAM roles) + Lambda code upload.
# Reproduces a working OpenSharing Volumes server in ~10 minutes.
#
# Prerequisites:
#   - AWS CLI configured with admin-level access
#   - Python 3.12+ with pip3
#   - An existing S3 Access Point (or FSx for ONTAP S3 AP) with data
#
# Usage:
#   ./deploy-lambda.sh --ap-alias <your-ap-alias>
#   ./deploy-lambda.sh --ap-alias my-ap-abc123-ext-s3alias --env prod
#   ./deploy-lambda.sh --destroy   # Tear down all resources
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REGION="${AWS_REGION:-ap-northeast-1}"
ENV="dev"
AP_ALIAS=""
DESTROY=false
STACK_NAME=""

# --- Parse arguments ---
while [[ $# -gt 0 ]]; do
  case $1 in
    --ap-alias) AP_ALIAS="$2"; shift 2 ;;
    --env) ENV="$2"; shift 2 ;;
    --region) REGION="$2"; shift 2 ;;
    --destroy) DESTROY=true; shift ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

STACK_NAME="opensharing-volumes-server-${ENV}"
FUNCTION_NAME="opensharing-volumes-server-${ENV}"
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
DEPLOY_BUCKET="fsxn-sam-deploy-${ACCOUNT_ID}"

# --- Destroy mode ---
if [ "$DESTROY" = true ]; then
  echo "=== Destroying OpenSharing Volumes Server ==="
  echo "Stack: $STACK_NAME"
  echo ""
  aws cloudformation delete-stack --stack-name "$STACK_NAME" --region "$REGION"
  echo "Waiting for stack deletion..."
  aws cloudformation wait stack-delete-complete --stack-name "$STACK_NAME" --region "$REGION" 2>/dev/null || true
  aws s3 rm "s3://${DEPLOY_BUCKET}/opensharing-server/" --recursive --region "$REGION" 2>/dev/null || true
  echo "✅ Destroyed"
  exit 0
fi

# --- Validate inputs ---
if [ -z "$AP_ALIAS" ]; then
  echo "ERROR: --ap-alias is required"
  echo "Usage: ./deploy-lambda.sh --ap-alias <your-s3-ap-alias>"
  echo ""
  echo "Example:"
  echo "  ./deploy-lambda.sh --ap-alias my-ap-abc123-ext-s3alias"
  exit 1
fi

echo "======================================================================="
echo "  OpenSharing Volumes Server — Lambda Deployment"
echo "  Stack:     $STACK_NAME"
echo "  Region:    $REGION"
echo "  AP Alias:  $AP_ALIAS"
echo "  Account:   $ACCOUNT_ID"
echo "======================================================================="
echo ""

# --- Step 1: Deploy CloudFormation (IAM roles + Lambda shell + Function URL) ---
echo "▶ Step 1: Deploying CloudFormation stack (IAM + Lambda + Function URL)..."
aws cloudformation deploy \
  --template-file "$SCRIPT_DIR/template.yaml" \
  --stack-name "$STACK_NAME" \
  --parameter-overrides \
    "S3AccessPointAlias=$AP_ALIAS" \
    "Environment=$ENV" \
  --capabilities CAPABILITY_NAMED_IAM \
  --region "$REGION" \
  --no-fail-on-empty-changeset

# Get outputs
VENDING_ROLE_ARN=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$REGION" \
  --query "Stacks[0].Outputs[?OutputKey=='VendingRoleArn'].OutputValue" --output text)
FUNC_URL=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$REGION" \
  --query "Stacks[0].Outputs[?OutputKey=='FunctionUrl'].OutputValue" --output text)

echo "   Vending Role: $VENDING_ROLE_ARN"
echo "   Function URL: $FUNC_URL"
echo ""

# --- Step 2: Generate volumes.yaml with actual values ---
echo "▶ Step 2: Generating config/volumes.yaml..."
cat > "$SCRIPT_DIR/config/volumes.yaml" << EOF
# Auto-generated by deploy-lambda.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
server:
  credential_duration_seconds: 900
  aws_region: ${REGION}
  sts_role_arn: ${VENDING_ROLE_ARN}

auth:
  tokens:
    - token: "test-quality-team-token"
      recipient: "quality-team"
      shares: ["factory"]
    - token: "test-engineering-token"
      recipient: "engineering"
      shares: ["factory"]
    - token: "test-unauthorized-token"
      recipient: "unauthorized-user"
      shares: []

shares:
  - name: factory
    comment: "Manufacturing data"
    schemas:
      - name: quality
        comment: "Quality inspection assets"
        volumes:
          - name: inspection-images
            comment: "Visual inspection photos"
            storage_location: "s3://${AP_ALIAS}/media/"
          - name: sensor-data
            comment: "Sensor readings (Parquet)"
            storage_location: "s3://${AP_ALIAS}/sensor-data/"
      - name: engineering
        comment: "Engineering documents"
        volumes:
          - name: delta-lake
            comment: "Delta Lake tables (read-only)"
            storage_location: "s3://${AP_ALIAS}/delta-lake/"
EOF
echo "   Generated with AP alias and vending role ARN"
echo ""

# --- Step 3: Package Lambda ---
echo "▶ Step 3: Packaging Lambda deployment..."
rm -rf "$SCRIPT_DIR/.lambda-pkg"
mkdir -p "$SCRIPT_DIR/.lambda-pkg"

pip3 install --target "$SCRIPT_DIR/.lambda-pkg" \
  fastapi mangum pyyaml \
  opentelemetry-api opentelemetry-sdk opentelemetry-instrumentation-fastapi \
  --quiet 2>/dev/null

cp -r "$SCRIPT_DIR/src" "$SCRIPT_DIR/.lambda-pkg/"
cp "$SCRIPT_DIR/lambda_handler.py" "$SCRIPT_DIR/.lambda-pkg/"
cp -r "$SCRIPT_DIR/config" "$SCRIPT_DIR/.lambda-pkg/"

cd "$SCRIPT_DIR/.lambda-pkg"
zip -r9 "$SCRIPT_DIR/deployment.zip" . -x "*.pyc" -x "__pycache__/*" -x "*.dist-info/*" > /dev/null
cd "$SCRIPT_DIR"
echo "   Package: $(du -sh deployment.zip | cut -f1)"
echo ""

# --- Step 4: Upload and update Lambda code ---
echo "▶ Step 4: Uploading Lambda code..."
aws s3 cp deployment.zip "s3://${DEPLOY_BUCKET}/opensharing-server/deployment.zip" \
  --region "$REGION" --quiet

aws lambda update-function-code \
  --function-name "$FUNCTION_NAME" \
  --s3-bucket "$DEPLOY_BUCKET" \
  --s3-key "opensharing-server/deployment.zip" \
  --region "$REGION" > /dev/null

echo "   Waiting for update..."
aws lambda wait function-updated-v2 --function-name "$FUNCTION_NAME" --region "$REGION"
echo "   ✅ Lambda updated"
echo ""

# --- Step 5: Verify ---
echo "▶ Step 5: Verifying deployment..."
sleep 2
HEALTH=$(curl -s "${FUNC_URL}health")
if echo "$HEALTH" | python3 -c "import json,sys; d=json.load(sys.stdin); assert d['status']=='healthy'" 2>/dev/null; then
  echo "   ✅ Health check passed"
else
  echo "   ❌ Health check failed: $HEALTH"
  exit 1
fi
echo ""

# --- Cleanup ---
rm -rf "$SCRIPT_DIR/.lambda-pkg" "$SCRIPT_DIR/deployment.zip"

# --- Summary ---
echo "======================================================================="
echo "  ✅ Deployment Complete"
echo ""
echo "  Function URL: $FUNC_URL"
echo "  Stack:        $STACK_NAME"
echo ""
echo "  Quick test:"
echo "    curl ${FUNC_URL}health"
echo "    curl -H 'Authorization: Bearer test-quality-team-token' \\"
echo "      ${FUNC_URL}api/v1/shares/factory/all-volumes"
echo ""
echo "  Full E2E test:"
echo "    python3 scripts/verify-deployment.py --url $FUNC_URL"
echo ""
echo "  Destroy:"
echo "    ./deploy-lambda.sh --destroy --env $ENV"
echo "======================================================================="
